    ZP_TMP2           = $19
    ZP_TMP            = $1A   
 
    KM_ERG	      = $1B
    KM_ERGHI          = $1C
    KM_X              = $1D
    KM_XHI            = $1E
    KM_Y              = $1F

    ZPG_STRPOINTER    = $20


    RGA_CURBANK       = $39
    RGA_VIDPOINTER    = $3A  ; two bytes
    RGA_VIDEOCOL      = $3C
    RGA_VIDEOROW      = $3D
    RGA_FGCOLOR       = $3E
    RGA_BGCOLOR       = $3F

